#!/usr/bin/env bash
# Set this checkout up for work: the pinned Haxe 5 compiler, the pinned library sources, and Haxe code
# intelligence for Serena. Run it once per checkout or worktree, and again after adding source files or
# changing a pin; restart Serena afterwards.
#
#   tools/setup.sh        # needs curl, sha256sum, tar, git, flock, node + npm
#
# - Compiler: the build of GeTechG/haxe named by tools/haxe-build.pin (`<build key> <sha256 of the archive>`),
#   downloaded from that repository's `builds` release, verified, and linked as the gitignored `.haxe`
#   (`.haxe/haxe`, `.haxe/std`). To change the compiler, change that file.
# - Libraries: every line of tools/libs.pin, fetched at its commit.
# - Language server: vshaxe/haxe-language-server built from source at LS_COMMIT. The published vshaxe
#   (2.34.2) starts the compiler with `--wait stdio`, which Haxe 5 dropped; this commit uses a socket.
# - Serena: the gitignored `.serena/lsp.hxml` (display config) and `.serena/project.local.yml`.
#
# Everything downloaded or built lives in ${XDG_CACHE_HOME:-~/.cache}/haxe-toolchain, one directory per
# build key or commit, shared by every checkout that pins the same one. Nothing there is removed automatically.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/haxe-toolchain"
LS_COMMIT=e865ce6ffa9299960d558728948691b7a5e9d4a2
LOCAL="$ROOT/.serena/project.local.yml"
MARK="# GENERATED by tools/setup.sh"

die() { echo "setup: $*" >&2; exit 1; }

# A file of comments only is the template Serena itself drops there; it holds nobody's settings.
if [ -f "$LOCAL" ] && grep -qv '^\s*\(#\|$\)' "$LOCAL" && ! grep -qF "$MARK" "$LOCAL"; then
  die "$LOCAL holds your own overrides; move them aside and re-run"
fi

read -r KEY SUM < "$ROOT/tools/haxe-build.pin"
[[ "$KEY" =~ ^[0-9a-f]{40}$ && "$SUM" =~ ^[0-9a-f]{64}$ ]] \
  || die "tools/haxe-build.pin must be one line: <build key, 40 hex> <sha256 of the archive, 64 hex>"

# One setup at a time per user: a second checkout waits here, then finds everything installed.
mkdir -p "$CACHE/haxe" "$CACHE/lib" "$CACHE/language-server"
exec 9> "$CACHE/.lock"
flock 9
TMP="$(mktemp -d "$CACHE/tmp.XXXXXX")"
trap 'rm -rf "$TMP"' EXIT

# Fetch one commit of a repository into a directory that appears only once complete.
fetch_commit() { # <url> <commit> <dir>
  [ -d "$3" ] && return
  rm -rf "$TMP/src"
  git init -q "$TMP/src"
  git -C "$TMP/src" fetch -q --depth 1 "$1" "$2"
  git -C "$TMP/src" checkout -q FETCH_HEAD
  mkdir -p "$(dirname "$3")"
  mv "$TMP/src" "$3"
}

# --- compiler
HAXE="$CACHE/haxe/$KEY"
if [ ! -x "$HAXE/haxe" ]; then
  ARCHIVE="haxe-linux64-$KEY.tar.gz"
  echo "setup: downloading $ARCHIVE ..."
  curl -fsSL --retry 3 -o "$TMP/$ARCHIVE" "https://github.com/GeTechG/haxe/releases/download/builds/$ARCHIVE" \
    || die "no $ARCHIVE in the builds release of GeTechG/haxe"
  GOT="$(sha256sum "$TMP/$ARCHIVE" | cut -d' ' -f1)"
  [ "$GOT" = "$SUM" ] || die "$ARCHIVE does not match tools/haxe-build.pin: expected $SUM, got $GOT"
  mkdir "$TMP/haxe"
  tar -xzf "$TMP/$ARCHIVE" -C "$TMP/haxe"
  [ -x "$TMP/haxe/haxe" ] && [ -d "$TMP/haxe/std" ] || die "$ARCHIVE holds no haxe + std/"
  rm -rf "$HAXE"
  mv "$TMP/haxe" "$HAXE"
fi
ln -sfn "$HAXE" "$ROOT/.haxe"
echo "setup: .haxe -> $HAXE ($("$HAXE/haxe" --version))"

# --- display config: classpaths, defines and every module of this repository's sources
mkdir -p "$ROOT/.serena/res"
{
  echo "$MARK — do not edit; re-run it after adding source files or changing a pin."
  echo "-cp $ROOT"
  # No -lib or --macro here: the language server passes these arguments to the compiler over a socket.
  grep -v '^\s*\(#\|$\)' "$ROOT/tools/libs.pin" | while read -r name version commit url cp; do
    fetch_commit "$url" "$commit" "$CACHE/lib/$name/$commit"
    echo "-cp $CACHE/lib/$name/$commit/$cp"
    echo "-D $name=$version"
  done
  echo "-D haxeui-heaps=$(sed -n 's/.*"version": *"\(.*\)".*/\1/p' "$ROOT/haxelib.json")"
  # heaps' hxd.Res scans a resource directory at compile time; a library has none, so give it an empty one.
  echo "-D resourcesPath=$ROOT/.serena/res"
  # The display server answers any warning as a failed request.
  echo "-w -WAll"
  echo "-hl .serena/lsp.hl"
  # Every module by name: with none listed the compiler's cache build types nothing and reference lookups
  # only know the files the session happened to open. `--macro include` fails in display mode.
  (cd "$ROOT" && find haxe -name '*.hx' ! -name import.hx | sed -e 's/\.hx$//' -e 's|/|.|g' | LC_ALL=C sort)
} > "$TMP/lsp.hxml"
mv "$TMP/lsp.hxml" "$ROOT/.serena/lsp.hxml"

# --- language server
LS="$CACHE/language-server/$LS_COMMIT"
if [ ! -f "$LS/bin/server.js" ]; then
  echo "setup: building haxe-language-server $LS_COMMIT ..."
  fetch_commit https://github.com/vshaxe/haxe-language-server "$LS_COMMIT" "$TMP/ls"
  (cd "$TMP/ls" && npm ci --silent && npx lix run vshaxe-build -t language-server > /dev/null)
  [ -f "$TMP/ls/bin/server.js" ] || die "the language server build produced no bin/server.js"
  mv "$TMP/ls" "$LS"
fi

# --- Serena. It overwrites project.local.yml when it has to generate a missing project.yml, so that one first.
[ -f "$ROOT/.serena/project.yml" ] || printf 'language_servers:\n- haxe\n' > "$ROOT/.serena/project.yml"
# The server reads no `haxePath` setting: it runs the `haxe` it finds on PATH.
cat > "$LOCAL" << YAML
$MARK — do not edit.
language_servers:
- haxe
ls_specific_settings:
  haxe:
    buildFile: .serena/lsp.hxml
    ls_base_cmd: ["sh", "-c", 'PATH="\$PWD/.haxe:\$PATH" HAXE_STD_PATH="\$PWD/.haxe/std" exec node "$LS/bin/server.js"']
    ls_args: []
YAML
echo "setup: Serena -> $LS/bin/server.js, $(grep -c '^haxe\.' "$ROOT/.serena/lsp.hxml") modules in .serena/lsp.hxml"

# A module that does not compile leaves the compiler's cache, and with it every reference lookup, incomplete.
(cd "$ROOT" && HAXE_STD_PATH=.haxe/std .haxe/haxe .serena/lsp.hxml --no-output) \
  || die "the sources do not compile with .serena/lsp.hxml: reference lookups will miss call sites until they do"
